Repository woowa-techcamp-2021/cashbook-14, pull requests merged in 2021-07, with the labels that each got.

#5 [chore] 전체적인 구조 세팅, 임시 코드 작성
  .eslintrc
  .prettierrc
  client/.babelrc
  client/assets/calendar.svg
  client/assets/chart.svg
  client/assets/check-large.svg
  client/assets/check-small.svg
  client/assets/delete.svg
  client/assets/file.svg
  client/assets/index.ts
  client/assets/left.svg
  client/assets/right.svg
  client/custom.d.ts
  client/package.json
  client/src/Components/atom/SaveButton/index.scss
  client/src/Components/atom/SaveButton/index.ts
  client/src/Components/molecule/Info/index.scss
  client/src/Components/molecule/Info/index.ts
  client/src/Pages/Main.ts
  client/src/core/Component.ts
  client/src/core/diff.ts
  client/src/core/jsx.ts
  client/src/core/parse.ts
  client/src/index.html
  client/src/index.ts
  client/src/lib/router.ts
  client/src/scss/animation.scss
  client/src/scss/index.scss
  client/src/scss/reset.scss
  client/src/scss/theme.scss
  client/src/util.ts
  client/tsconfig.json
  client/webpack.config.js
  client/yarn.lock
  script/deploy.sh
  server/app.ts
  server/controllers/UserController.ts
  server/database.ts
  server/middlewares/authenticate.ts
  server/models/history.ts
  server/models/payment.ts
  server/models/user.ts
  server/package.json
  server/routes/index.ts
  server/services/UserService.ts
  server/tsconfig.json
  server/yarn.lock
Labels: backend, enhancement, frontend

#6 [feature] 컴포넌트 마크업
  client/assets/.svg
  client/assets/calendar.svg
  client/assets/chart.svg
  client/assets/check-small.svg
  client/assets/file.svg
  client/assets/index.ts
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/Header/style.scss
  client/src/Components/atom/SaveButton/index.scss
  client/src/Components/atom/SaveButton/index.ts
  client/src/Components/atom/SaveButton/style.scss
  client/src/Pages/Main.ts
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/core/Component.ts
  client/src/core/jsx.ts
  client/src/scss/index.scss
  client/src/scss/theme.scss
  client/tsconfig.json
Labels: enhancement, frontend

#7 [feature] 컴포넌트 작성
  client/src/Components/atom/CategoryTag/index.ts
  client/src/Components/atom/CategoryTag/style.scss
  client/src/Components/atom/DayList/index.ts
  client/src/Components/atom/DayList/style.scss
  client/src/Components/atom/SaveButton/index.ts
  client/src/Components/atom/SaveButton/style.scss
  client/src/Components/atom/TextInput/index.ts
  client/src/Components/atom/TextInput/style.scss
  client/src/Components/molecule/Alert/index.ts
  client/src/Components/molecule/Alert/style.scss
  client/src/Components/molecule/Info/index.scss
  client/src/Components/molecule/Info/index.ts
  client/src/Components/molecule/Info/style.scss
  client/src/Components/molecule/InputBar/index.ts
  client/src/Components/molecule/InputBar/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/scss/index.scss
  client/src/scss/theme.scss
Labels: enhancement, frontend

#9 [feature] 메인 화면 전체적인 마크업 완료
  client/assets/drop.svg
  client/assets/index.ts
  client/src/Components/atom/CategoryTag/index.ts
  client/src/Components/atom/CategoryTag/style.scss
  client/src/Components/atom/Dropdown/index.ts
  client/src/Components/atom/Dropdown/style.scss
  client/src/Components/atom/Header/index.ts
  client/src/Components/molecule/InputBar/index.ts
  client/src/Components/molecule/InputBar/input.ts
  client/src/Components/molecule/InputBar/select.ts
  client/src/Components/molecule/InputBar/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Calendar/style.scss
  client/src/Pages/Chart/index.ts
  client/src/Pages/Chart/style.scss
  client/src/Pages/Main/index.ts
  client/src/core/Component.ts
  client/src/core/jsx.ts
  client/src/core/parse.ts
  client/src/index.html
  client/src/index.ts
  client/src/lib/router.ts
  client/src/scss/theme.scss
Labels: enhancement, frontend

#11 [feature] calendar 구현
  client/src/Components/atom/Calendar/index.ts
  client/src/Components/atom/Calendar/style.scss
  client/src/Components/atom/Header/index.ts
  client/src/Controller/calendar.ts
  client/src/Controller/index.ts
  client/src/Model/date.ts
  client/src/Model/index.ts
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Calendar/style.scss
  client/src/core/Component.ts
  client/src/scss/index.scss
  client/src/scss/theme.scss
  client/src/util.ts
  client/src/utils/observer.ts
Labels: enhancement, frontend

#12 [feature] API 완성
  server/controllers/AuthController.ts
  server/controllers/CategoryController.ts
  server/controllers/HistoryController.ts
  server/controllers/MeController.ts
  server/controllers/PaymentController.ts
  server/middlewares/authenticate.ts
  server/routes/me.ts
  server/services/CategoryService.ts
  server/services/HistoryService.ts
  server/services/PaymentService.ts
  server/types/express.d.ts
Labels: backend, enhancement

#13 [feature] color picker 구현
  client/assets/.svg
  client/assets/index.ts
  client/assets/refresh.svg
  client/src/Components/atom/Calendar/index.ts
  client/src/Components/atom/Calendar/style.scss
  client/src/Components/atom/ColorPicker/index.ts
  client/src/Components/atom/ColorPicker/style.scss
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/Header/style.scss
  client/src/Components/atom/TextInput/index.ts
  client/src/Components/molecule/Alert/index.ts
  client/src/Components/molecule/Alert/style.scss
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Calendar/style.scss
  client/src/Pages/Chart/index.ts
  client/src/Pages/Chart/style.scss
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/index.html
  client/src/scss/animation.scss
  client/src/scss/index.scss
  client/src/utils/observer.ts
  client/src/utils/util.ts
Labels: enhancement, frontend

#14 [feature] 캘린더 애니메이션
  client/api/auth.ts
  client/api/category.ts
  client/api/history.ts
  client/api/me.ts
  client/api/payment.ts
  client/src/Components/atom/Calendar/index.ts
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Main/style.scss
  client/src/index.html
  client/src/scss/animation.scss
Labels: enhancement, frontend

#15 [feat] database table 수정 및 타입 변경
  server/controllers/AuthController.ts
  server/controllers/CategoryController.ts
  server/controllers/HistoryController.ts
  server/controllers/MeController.ts
  server/controllers/PaymentController.ts
  server/middlewares/authenticate.ts
  server/models/category.ts
  server/models/history.ts
  server/models/payment.ts
  server/models/user.ts
  server/routes/auth.ts
  server/services/CategoryService.ts
  server/services/HistoryService.ts
  server/services/PaymentService.ts
  server/services/UserService.ts
Labels: backend, enhancement

#16 [feature] github oauth 완료
  client/package.json
  client/src/Components/molecule/InputBar/index.ts
  client/src/Components/molecule/list/index.ts
  client/src/Pages/Main/index.ts
  client/yarn.lock
  server/app.ts
  server/controllers/AuthController.ts
  server/controllers/MeController.ts
  server/middlewares/authenticate.ts
  server/models/history.ts
  server/models/payment.ts
  server/models/user.ts
  server/package.json
  server/routes/auth.ts
  server/routes/github.ts
  server/routes/index.ts
  server/services/AuthService.ts
  server/services/JwtService.ts
  server/services/PaymentService.ts
  server/services/UserService.ts
  server/third-party/github.ts
  server/yarn.lock
Labels: backend, enhancement

#18 [feat] 원그래프 및 ChartPage 틀
  client/src/Components/atom/PieGraph/index.ts
  client/src/Components/atom/PieGraph/style.scss
  client/src/Pages/Chart/index.ts
  client/src/Pages/Chart/style.scss
Labels: enhancement, frontend

#19 [feature] 모델 일부 수정, getMyHistories 결과 변경
  server/controllers/MeController.ts
  server/models/history.ts
  server/models/payment.ts
  server/services/CategoryService.ts
  server/services/HistoryService.ts
  server/services/PaymentService.ts
Labels: backend, enhancement

#20 [fix] githubName이 null 경우 githubId를 복사하여 사용
  server/controllers/AuthController.ts
Labels: backend, enhancement

#24 [feature] GET histories with totalCount
  server/controllers/MeController.ts
Labels: backend, enhancement
