Repository woowa-techcamp-2021/cashbook-14, pull requests merged in 2021-08, with the labels that each got.

#25 [feature] GET histories with total(In|Out)comeCount
  server/controllers/MeController.ts
Labels: backend, enhancement

#23 [feature] 컴포넌트 분리 및 리렌더링 버그 해결
  client/assets/github.svg
  client/assets/index.ts
  client/src/Components/atom/Calendar/index.ts
  client/src/Components/atom/Calendar/style.scss
  client/src/Components/atom/CategoryTag/index.ts
  client/src/Components/atom/DayList/index.ts
  client/src/Components/atom/Dropdown/index.ts
  client/src/Components/atom/Dropdown/style.scss
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/InputBarInput/index.ts
  client/src/Components/atom/InputBarInput/style.scss
  client/src/Components/atom/InputBarSelect/index.ts
  client/src/Components/atom/InputBarSelect/style.scss
  client/src/Components/molecule/Alert/index.ts
  client/src/Components/molecule/Alert/style.scss
  client/src/Components/molecule/Info/index.ts
  client/src/Components/molecule/InputBar/index.ts
  client/src/Components/molecule/InputBar/select.ts
  client/src/Components/molecule/InputBar/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/CalendarContainer/index.ts
  client/src/Components/organism/CalendarContainer/style.scss
  client/src/Components/organism/historyList/index.ts
  client/src/Controller/calendar.ts
  client/src/Model/index.ts
  client/src/Model/user.ts
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Calendar/style.scss
  client/src/Pages/Chart/index.ts
  client/src/Pages/Chart/style.scss
  client/src/Pages/Login/index.ts
  client/src/Pages/Login/style.scss
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/api/me.ts
  client/src/core/Component.ts
  client/src/index.ts
  client/src/scss/animation.scss
  client/src/shared/type.ts
  client/src/utils/util.ts
  server/app.ts
  server/controllers/AuthController.ts
  server/controllers/MeController.ts
  server/database.ts
  server/middlewares/authenticate.ts
  server/models/history.ts
  server/package.json
  server/routes/category.ts
  server/routes/history.ts
  server/routes/index.ts
  server/routes/payment.ts
  server/services/HistoryService.ts
  server/services/UserService.ts
Labels: enhancement, frontend

#33 [feature] 캘린더 detail slide & 카테고리 dropdown 색상 노출
  client/src/Components/atom/Calendar/index.ts
  client/src/Components/molecule/Calendar/index.ts
  client/src/Components/molecule/Calendar/style.scss
  client/src/Components/molecule/DetailInfo/index.ts
  client/src/Components/molecule/DetailInfo/style.scss
  client/src/Components/molecule/Dropdown/index.ts
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/organism/CalendarContainer/index.ts
  client/src/Components/organism/InputBar/index.ts
  client/src/Components/organism/historyList/index.ts
  client/src/Components/organism/historyList/style.scss
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/api/history.ts
  client/src/scss/animation.scss
  client/src/scss/index.scss
  server/services/HistoryService.ts
Labels: enhancement, frontend

#35 [feature] date 셀렉터 구현 / header의 date 분리 / 텍스트 애니메이션 추가
  client/assets/arrow.svg
  client/assets/github.svg
  client/assets/index.ts
  client/src/Components/atom/DateSelect/index.ts
  client/src/Components/atom/DateSelect/style.scss
  client/src/Components/atom/DayList/index.ts
  client/src/Components/atom/Header/date.ts
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/Header/style.scss
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/organism/historyList/index.ts
  client/src/Controller/calendar.ts
  client/src/Pages/Login/index.ts
  client/src/Pages/Login/style.scss
  client/src/scss/animation.scss
  client/src/scss/index.scss
Labels: enhancement, frontend

#36 [feat] dark mode
  .gitignore
  client/assets/moon.svg
  client/assets/sun.svg
  client/src/Components/atom/ColorPicker/style.scss
  client/src/Components/atom/DateSelect/style.scss
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/Header/style.scss
  client/src/Components/molecule/Calendar/style.scss
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/CalendarContainer/style.scss
  client/src/Components/organism/InputBar/style.scss
  client/src/core/router.ts
  client/src/index.html
  client/src/index.ts
  client/src/scss/index.scss
  client/src/scss/theme.scss
  client/src/shared/type.ts
Labels: enhancement, frontend

#38 [feature] 메인/캘린더 모바일뷰 구현
  client/src/Components/atom/CategoryTag/style.scss
  client/src/Components/atom/DayList/style.scss
  client/src/Components/atom/Header/style.scss
  client/src/Components/molecule/Calendar/index.ts
  client/src/Components/molecule/Calendar/style.scss
  client/src/Components/molecule/DetailInfo/style.scss
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/molecule/Info/style.scss
  client/src/Components/molecule/InputBarSelect/style.scss
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/CalendarContainer/style.scss
  client/src/Components/organism/ChartContainer/style.scss
  client/src/Components/organism/InputBar/index.ts
  client/src/Components/organism/InputBar/style.scss
  client/src/Components/organism/historyList/style.scss
  client/src/Pages/Calendar/index.ts
  client/src/Pages/Chart/index.ts
  client/src/Pages/Main/index.ts
  client/src/Pages/Main/style.scss
  client/src/index.html
  client/src/scss/animation.scss
  client/src/scss/index.scss
  client/src/scss/theme.scss
Labels: enhancement, frontend

#39 [feature] ChartPage
  client/src/Components/atom/LinearGraph/configType.ts
  client/src/Components/atom/LinearGraph/defaultConfig.ts
  client/src/Components/atom/LinearGraph/index.ts
  client/src/Components/atom/LinearGraph/style.scss
  client/src/Components/atom/PieGraph/configType.ts
  client/src/Components/atom/PieGraph/defaultConfig.ts
  client/src/Components/atom/PieGraph/index.ts
  client/src/Components/molecule/Chart/index.ts
  client/src/Components/molecule/Chart/style.scss
  client/src/Components/molecule/LinearGraphWrapper/index.ts
  client/src/Components/molecule/LinearGraphWrapper/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Components/organism/ChartContainer/index.ts
  client/src/Components/organism/ChartContainer/style.scss
  client/src/api/me.ts
  client/src/shared/type.ts
Labels: enhancement, frontend

#40 [feature] 로그인 페이지 모바일뷰 & env 분리
  client/src/Components/atom/Header/style.scss
  client/src/Components/molecule/DetailInfo/style.scss
  client/src/Pages/Login/style.scss
  client/src/scss/animation.scss
  server/app.ts
  server/controllers/AuthController.ts
  server/package.json
Labels: backend, enhancement, frontend

#41 [feature] env 분리 / 라우팅 수정 / 정규식 / popstate
  .gitignore
  client/package.json
  client/src/Components/atom/DateSelect/style.scss
  client/src/Components/atom/Header/style.scss
  client/src/Components/atom/InputBarInput/style.scss
  client/src/Components/molecule/Calendar/style.scss
  client/src/Components/molecule/DetailInfo/index.ts
  client/src/Components/molecule/DetailInfo/style.scss
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/molecule/Info/style.scss
  client/src/Components/organism/CalendarContainer/style.scss
  client/src/Components/organism/InputBar/index.ts
  client/src/Components/organism/InputBar/style.scss
  client/src/Components/organism/historyList/style.scss
  client/src/Pages/Login/index.ts
  client/src/Pages/Main/style.scss
  client/src/core/router.ts
  client/src/utils/util.ts
  client/webpack.config.js
  client/yarn.lock
  server/app.ts
  server/controllers/AuthController.ts
  server/envConfig.ts
Labels: backend, bug, enhancement, frontend

#42 [feature] input bar 리팩토링 및 버튼 활성화 체크
  client/assets/check-disabled.svg
  client/assets/check-small.svg
  client/assets/check.svg
  client/assets/index.ts
  client/src/Components/atom/Header/index.ts
  client/src/Components/atom/InputBarInput/index.ts
  client/src/Components/atom/SaveButton/index.ts
  client/src/Components/atom/SaveButton/style.scss
  client/src/Components/molecule/Alert/style.scss
  client/src/Components/molecule/Dropdown/index.ts
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/molecule/InputBarSelect/index.ts
  client/src/Components/organism/InputBar/CreateBtn/index.ts
  client/src/Components/organism/InputBar/InputBarInput/index.ts
  client/src/Components/organism/InputBar/InputBarInput/style.scss
  client/src/Components/organism/InputBar/InputBarSelect/index.ts
  client/src/Components/organism/InputBar/InputBarSelect/style.scss
  client/src/Components/organism/InputBar/PaymentTypeBtn/index.ts
  client/src/Components/organism/InputBar/index.ts
  client/src/Components/organism/InputBar/style.scss
  client/src/Model/historyInput.ts
  client/src/Model/index.ts
  client/src/core/Component.ts
  client/src/shared/type.ts
Labels: enhancement, frontend

#43 [fix] save history with formatted date
  server/services/HistoryService.ts
Labels: backend, bug, enhancement

#44 [feature] ChartPage
  client/src/Components/molecule/Chart/index.ts
  client/src/Components/molecule/Chart/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/ChartContainer/index.ts
  client/src/Components/organism/ChartContainer/style.scss
  client/src/Components/organism/historyList/index.ts
  client/src/Pages/Main/style.scss
  client/src/scss/index.scss
Labels: enhancement, frontend

#45 [feature] 내역 삭제 구현 / css 버그 픽스
  client/src/Components/atom/DateSelect/style.scss
  client/src/Components/atom/LinearGraph/style.scss
  client/src/Components/molecule/DetailInfo/style.scss
  client/src/Components/molecule/Info/index.ts
  client/src/Components/molecule/list/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/CalendarContainer/style.scss
  client/src/Components/organism/ChartContainer/index.ts
  client/src/Components/organism/InputBar/InputBarInput/index.ts
  client/src/Components/organism/InputBar/index.ts
  client/src/Components/organism/InputBar/style.scss
  client/src/Components/organism/historyList/index.ts
  client/src/api/history.ts
  client/src/scss/animation.scss
Labels: bug, enhancement, frontend

#46 [feature] ChartPage DayList 제거, ProgressBar 변경 및 기타 의견 반영
  client/src/Components/atom/PieGraph/index.ts
  client/src/Components/molecule/Chart/index.ts
  client/src/Components/molecule/Chart/style.scss
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/ChartContainer/style.scss
Labels: enhancement, frontend

#47 [feature] CSS 수정 / 더미데이터
  client/src/Components/molecule/Chart/index.ts
  client/src/Components/molecule/Chart/style.scss
  client/src/Components/molecule/Dropdown/index.ts
  client/src/Components/molecule/Info/index.ts
  client/src/Components/molecule/Info/style.scss
  client/src/Components/molecule/list/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Components/organism/InputBar/InputBarInput/style.scss
  client/src/Components/organism/InputBar/InputBarSelect/index.ts
  client/src/Pages/Main/style.scss
  client/src/scss/index.scss
  server/controllers/AuthController.ts
Labels: backend, enhancement, frontend

#48 [bug] 캘린더 페이지 렌더링 버그 픽스
  client/src/Components/molecule/Calendar/calBody.ts
  client/src/Components/molecule/Calendar/detailSlide.ts
  client/src/Components/molecule/Calendar/index.ts
  client/src/Components/molecule/DetailInfo/index.ts
  client/src/Components/molecule/list/style.scss
  client/src/Model/historyDetail.ts
  client/src/Model/index.ts
Labels: bug

#49 [refactor] 리팩토링
  client/src/Components/atom/LinearGraph/defaultConfig.ts
  client/src/Components/atom/LinearGraph/index.ts
Labels: enhancement

#50 [fix] category와 payment가 null인 history 렌더링이 안되는 버그 수정
  client/src/Components/molecule/DetailInfo/index.ts
  client/src/Components/molecule/list/index.ts
  client/src/Components/organism/ChartContainer/index.ts
  client/src/Components/organism/historyList/index.ts
Labels: enhancement, frontend

#51 [fix] 다크모드에서 분류 및 결제수단 등록 삭제 시 글자 안보이는 문제 해결
  client/src/Components/atom/TextInput/style.scss
Labels: bug, frontend

#54 [fix] 데모 전 버그 픽스
  client/src/Components/molecule/Alert/index.ts
  client/src/Components/molecule/Dropdown/style.scss
  client/src/Components/organism/InputBar/index.ts
Labels: bug, frontend
